### ISSUE TITLE
Use placeholder classnames

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/jest-glamor-react#11]
See [this](https://github.com/styled-components/jest-styled-components/pull/31). Doing this could significantly improve code reviews and avoid this problem:

<img width="362" alt="screen shot 2017-06-26 at 4 20 55 pm" src="https://user-images.githubusercontent.com/1500684/27562792-79387eb0-5a8b-11e7-9245-bcafccbad6d0.png">

Notice that none of those rules changed. So it's just noise in the diff. Would be much nicer to only see the diff where it changed.

Though, that could present other problems. Like what happens when I add another styled component into the mix? That would bump all of the placeholders up. Would that be all that bad though 🤔. Perhaps @MicheleBertoli can share some thoughts

**Comment by kentcdodds** [comment]
Anyone can feel free to help with this. Please just follow [the contributing guidelines](https://github.com/kentcdodds/jest-glamor-react/blob/master/CONTRIBUTING.md)

**Comment by Oalbacha** [comment]
I would like to take a stab at it.

**Comment by Oalbacha** [comment]
Is this the first timer friendly issue?

**Comment by kentcdodds** [comment]
I don't think I'd say it's really first-timer friendly, but you could definitely give it a try! [this](https://github.com/styled-components/jest-styled-components/blob/de7e6a28e5e4053e61b1d5b09f006e73dd2ef1d3/src/serializers/styleSheetSerializer.js#L36-L48) might be inspiring...
