### ISSUE TITLE
Setup instructions unclear

### ISSUE THREAD

**Issue by lopis** [kentcdodds/jest-glamor-react#2]
Thanks for putting the time to release this jest module. The first step in the instructions is

```
At the top of your test file:

import {matcher, serializer} from '../src'
expect.addSnapshotSerializer(serializer)
expect.extend(matcher)
```

I feel like I'm missing something. Where do `matcher` and `serializer` come from? I'm using `create-react-app` in my project, if that's worth mentioning. As it is, jest complains that it "Cannot find module `../../src`".

**Comment by kentcdodds** [comment]
Sorry, my bad, the docs have been updated. Good luck!

**Comment by lopis** [comment]
@kentcdodds Thanks for the fast reply, I think it works. Just need to figure out the second error.
