### ISSUE TITLE
`snapshotSerializers` failing on CI

### ISSUE THREAD

**Issue by kirkstrobeck** [kentcdodds/jest-glamor-react#20]
- `jest-glamor-react` version: 3.1.0
- `node` version: 8.1.2
- `npm` (or `yarn`) version: 0.24.6

### Relevant code or config:

```json
{
    "snapshotSerializers": [
      "jest-glamor-react"
    ]
}
```

### What you did:

Code was working as expected, then after updating the following packages:

```json
{
  "@storybook/addon-actions": "^3.2.10",
  "@storybook/addon-links": "^3.2.10",
  "@storybook/addon-options": "^3.2.10",
  "@storybook/addons": "^3.2.10",
  "@storybook/react": "^3.2.10"
}
```

to

```json
{
  "@storybook/addon-actions": "^3.2.10",
  "@storybook/addon-links": "^3.2.10",
  "@storybook/addon-options": "^3.2.10",
  "@storybook/addons": "^3.2.10",
  "@storybook/react": "^3.2.10"
}
```

### What happened:

Appears to be non-functional

```bash
-      className="glamor-0"
+      className="css-1139u7f"
```

### Problem description:

In an attempt to diagnose, I cloned a fork locally and when linking via `yarn` I can reproduce the issue. If I link via `npm` the issue goes away.

### Suggested solution:

I assume this has something to do with the way that `yarn` makes this lib is made available to `jest` as a custom serializer.

**Comment by kentcdodds** [comment]
Interesting. Thanks for filing the issue @kirkstrobeck!

I don't use `yarn`, so I wont be looking into this myself. If you could dig a little further to figure out whether we can fix this issue or if it's something we need a workaround for to document, then let's make that happen.

Good luck! And thanks!

**Comment by kirkstrobeck** [comment]
Hmm, after a bit more investigation using `npm install` on CI still reproduces the error, so may not be a `yarn` vs. `npm` issue.

**Comment by hjylewis** [comment]
I am having the same issue where it works locally but not running on CI.

```
FAIL  src/components/Text/Text.test.js
  ● <Text /> › matches snapshot

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    -.css-sj857o,
    -[data-css-sj857o] {
    -  font-size: 16px;
    -  line-height: inherit;
    -}
    -
     <span
       data-css-sj857o=""
     >
       Hello, World
     </span>
```

**Comment by kirkstrobeck** [comment]
@hjylewis are you using `yarn` or `npm`?

**Comment by hjylewis** [comment]
@kirkstrobeck I'm using `npm`

**Comment by lewisl9029** [comment]
I haven't had a chance to look into how this could happen yet, but we seem to be able to reproduce this only if the following are true: 1) `--coverage` flag is enabled for Jest, 2) `NODE_ENV` is set to `production`.

**Comment by kentcdodds** [comment]
That's weird... Sorry, I'm not sure what's going on there :-/

**Comment by hjylewis** [comment]
OK! so I discovered it fails for me when `NODE_ENV=production`. In other words:
* `NODE_ENV=production npm test` => FAIL
* `npm test` => SUCCESS

And our Jenkins and other CI probably set the environment to production.

Is glamor or this library is doing things differently when it detects a production env?

**Comment by hjylewis** [comment]
I believe it has to do with glamor's [speedy functionality](https://github.com/threepointone/glamor#speedy-mode)

**Comment by hjylewis** [comment]
SO! That was an issue but ultimately a different issue was causing the failure on Jenkins.

## Problem 
In order for `jest-glamor-react` to get the correct styleSheet, it needs to be using the same instance of `glamor` that `jest` is using.

But when there are different versions, npm/yarn will add a different `glamor` to `node_modules/jest-glamor-react/node_modules` for this library to use. This results in `jest-glamor-react` looking at an empty styleSheet

## Solution
I believe the solution to this problem would be changing `glamor` to a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) so that the same instance is used.

**Comment by kirkstrobeck** [comment]
Not sure that is the solution, since https://github.com/kentcdodds/jest-glamor-react/blob/master/package.json#L57-L59

**Comment by hjylewis** [comment]
Yeah, just noticed that. The solution might be removing the `glamor` dependency and leaving the peer one. Haven't tried just yet but that might stop it from installing its own version.

**Comment by kentcdodds** [comment]
Yeah, we could probably remove it from the dependencies and publish a new version without bumping the major version because I doubt anyone using this doesn't have glamor already. Anyone want to do that?

**Comment by hjylewis** [comment]
I think that would work..

Or, since this package still uses `glamor` for some tests, we can move it to a dev dependency so that it doesn't get installed transitively when this package is included as a dependency.

Does that make sense? I'm still wrapping my head around all these dependency stuff.

**Comment by kentcdodds** [comment]
Yep, let's move it to devDependencies 👍

**Comment by hjylewis** [comment]
@kirkstrobeck does that fix your issue? you will have to `rm -rf node_modules/` and re `npm install`

**Comment by kentcdodds** [comment]
Try upgrading to the latest version (v4) and see if this issue's resolved.
