### ISSUE TITLE
css- prefixed selectors are not replaced if the component has no styles

### ISSUE THREAD

**Issue by rszewczyk** [kentcdodds/jest-glamor-react#27]
- `jest-glamor-react` version: 3.2.2
- `node` version: 8.9.0
- `npm` (or `yarn`) version: yarn 1.3.2

Relevant code or config

I created a [repo that demonstrates the problem](https://github.com/rszewczyk/glamor-jest-demo).

If a component that has selectors prefixed with `css-` but the component does not have any styles associated with those selectors, the selectors will not be replaced in the snapshot. I realize this sounds weird, but Emotion will add selectors like this when using its `styled` utility and the `babel-plugin-emotion`. 

You can see a contrived example [here](https://github.com/rszewczyk/glamor-jest-demo/blob/master/__snapshots__/components-glamor.test.js.snap). Note that as long as at least one selector has styles associated with it, all of the `css-` prefixed selectors get replaced. It's only when none of the selectors are in the stylesheet that it doesn't rewrite them.

[Here is an example with Emotion](https://github.com/rszewczyk/glamor-jest-demo/blob/master/__snapshots__/components-emotion.test.js.snap).

Suggested Fix:
I'm going to submit a PR shortly.

**Comment by kentcdodds** [comment]
This should be resolved in v4
