### ISSUE TITLE
Support expect matchers on value field

### ISSUE THREAD

**Issue by Ailrun** [kentcdodds/jest-glamor-react#36]
* `jest-glamor-react` version: v4.2.1
* `node` version: v8.11.1
* `npm` (or `yarn`) version: v5.8.0

Relevant code or config

```javascript
it('could accept expect matchers', () => {
  expect(component).toHaveStyleRule('position', expect.anything());
});
```

https://github.com/kentcdodds/jest-glamor-react/blob/21fdeffd2de3a11430554f4be08ccc6562a17aa7/src/matchers.js#L6-L10

Problem description:
toHaveStyleRule accepts only `RegExp` or `String`

Suggested solution:
Add https://github.com/facebook/jest/tree/master/packages/expect as a dependency and use `expect` to check equivalence.

P.S. Could I make a PR for this?

**Comment by kentcdodds** [comment]
Sure! This sounds great!
