### ISSUE TITLE
Support providing custom StyleSheet instance.

### ISSUE THREAD

**Issue by tkh44** [kentcdodds/jest-glamor-react#5]
Since there are multiple libraries out there that are built on glamor, if you allow the user to pass in the instance of `StyleSheet` from their lib you can support them all!

If this sounds like something you would like to add I can do most of the legwork. I have already tested this with cxs to test `restyles`.

**Comment by tkh44** [comment]
Maybe something like
```
import { sheet } from 'cxs'
expect.addSnapshotSerializer(serializer(sheet))
...
```

**Comment by kentcdodds** [comment]
Sounds great! Though I'd prefer to not break the current API. If you can make that work, let's do it!
