### ISSUE TITLE
Last release failed

### ISSUE THREAD

**Issue by chambo-e** [kentcdodds/jest-glamor-react#7]
Hello, 
The last automated release has failed [here](https://travis-ci.org/kentcdodds/jest-glamor-react/jobs/236113195)

Would be nice to have #6 :)

Thanks !

**Comment by kentcdodds** [comment]
Sorry about that. GitHub's UI for squash and merge has a bug in it where the commit message I set doesn't get applied :-( Hopefully that's resolved soon. I've had to do manual releases quite a bit recently (I never have to do this).
