### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by rockchalkwushock** [kentcdodds/jest-glamor-react#8]
Just wanted to say thanks for this package! I'm just getting into using `jest` to actually test what is being rendered to the DOM instead of only the logic in my applications. I didn't have the slightest idea how to do so but the `with-jest` example in `glamorous` and this package have helped me immensely! 👍  💯

**Comment by kentcdodds** [comment]
That's awesome! Thank you so much for letting me know. This is my favorite kind of issue <3
